//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the ptam package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __ptam__PTAMPARAMSCONFIG_H__
#define __ptam__PTAMPARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace ptam
{
  class PtamParamsConfigStatics;

  class PtamParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(PtamParamsConfig &config, const PtamParamsConfig &max, const PtamParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PtamParamsConfig &config1, const PtamParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PtamParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PtamParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PtamParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PtamParamsConfig &config) const = 0;
      virtual void getValue(const PtamParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PtamParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (PtamParamsConfig::* field);

      virtual void clamp(PtamParamsConfig &config, const PtamParamsConfig &max, const PtamParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PtamParamsConfig &config1, const PtamParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PtamParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PtamParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PtamParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PtamParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PtamParamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PtamParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PtamParamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<PtamParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PtamParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Scale"==(*_i)->name){Scale = boost::any_cast<double>(val);}
        if("MotionModelSource"==(*_i)->name){MotionModelSource = boost::any_cast<std::string>(val);}
        if("MaxPatchesPerFrame"==(*_i)->name){MaxPatchesPerFrame = boost::any_cast<double>(val);}
        if("MaxKFDistWiggleMult"==(*_i)->name){MaxKFDistWiggleMult = boost::any_cast<double>(val);}
        if("UseKFPixelDist"==(*_i)->name){UseKFPixelDist = boost::any_cast<bool>(val);}
        if("NoLevelZeroMapPoints"==(*_i)->name){NoLevelZeroMapPoints = boost::any_cast<bool>(val);}
        if("EpiDepthSearchMaxRange"==(*_i)->name){EpiDepthSearchMaxRange = boost::any_cast<double>(val);}
        if("CoarseMin"==(*_i)->name){CoarseMin = boost::any_cast<double>(val);}
        if("CoarseMax"==(*_i)->name){CoarseMax = boost::any_cast<double>(val);}
        if("CoarseRange"==(*_i)->name){CoarseRange = boost::any_cast<double>(val);}
        if("CoarseSubPixIts"==(*_i)->name){CoarseSubPixIts = boost::any_cast<double>(val);}
        if("DisableCoarse"==(*_i)->name){DisableCoarse = boost::any_cast<bool>(val);}
        if("CoarseMinVelocity"==(*_i)->name){CoarseMinVelocity = boost::any_cast<double>(val);}
        if("TrackingQualityGood"==(*_i)->name){TrackingQualityGood = boost::any_cast<double>(val);}
        if("TrackingQualityLost"==(*_i)->name){TrackingQualityLost = boost::any_cast<double>(val);}
        if("TrackingQualityFoundPixels"==(*_i)->name){TrackingQualityFoundPixels = boost::any_cast<int>(val);}
        if("MaxIterations"==(*_i)->name){MaxIterations = boost::any_cast<double>(val);}
        if("MaxKF"==(*_i)->name){MaxKF = boost::any_cast<int>(val);}
        if("BundleMethod"==(*_i)->name){BundleMethod = boost::any_cast<std::string>(val);}
        if("UpdateSquaredConvergenceLimit"==(*_i)->name){UpdateSquaredConvergenceLimit = boost::any_cast<double>(val);}
        if("BundleDebugMessages"==(*_i)->name){BundleDebugMessages = boost::any_cast<bool>(val);}
        if("FASTMethod"==(*_i)->name){FASTMethod = boost::any_cast<std::string>(val);}
        if("Thres_lvl0"==(*_i)->name){Thres_lvl0 = boost::any_cast<int>(val);}
        if("Thres_lvl1"==(*_i)->name){Thres_lvl1 = boost::any_cast<int>(val);}
        if("Thres_lvl2"==(*_i)->name){Thres_lvl2 = boost::any_cast<int>(val);}
        if("Thres_lvl3"==(*_i)->name){Thres_lvl3 = boost::any_cast<int>(val);}
        if("AdaptiveThrs"==(*_i)->name){AdaptiveThrs = boost::any_cast<bool>(val);}
        if("AdaptiveThrsMult"==(*_i)->name){AdaptiveThrsMult = boost::any_cast<double>(val);}
        if("RotationEstimatorBlur"==(*_i)->name){RotationEstimatorBlur = boost::any_cast<double>(val);}
        if("UseRotationEstimator"==(*_i)->name){UseRotationEstimator = boost::any_cast<bool>(val);}
        if("MiniPatchMaxSSD"==(*_i)->name){MiniPatchMaxSSD = boost::any_cast<int>(val);}
        if("PlaneAlignerRansacs"==(*_i)->name){PlaneAlignerRansacs = boost::any_cast<int>(val);}
        if("RelocMaxScore"==(*_i)->name){RelocMaxScore = boost::any_cast<int>(val);}
        if("AutoInit"==(*_i)->name){AutoInit = boost::any_cast<bool>(val);}
        if("CheckInitMapVar"==(*_i)->name){CheckInitMapVar = boost::any_cast<bool>(val);}
        if("AutoInitPixel"==(*_i)->name){AutoInitPixel = boost::any_cast<int>(val);}
        if("MaxStereoInitLoops"==(*_i)->name){MaxStereoInitLoops = boost::any_cast<int>(val);}
      }
    }

    double Scale;
std::string MotionModelSource;
double MaxPatchesPerFrame;
double MaxKFDistWiggleMult;
bool UseKFPixelDist;
bool NoLevelZeroMapPoints;
double EpiDepthSearchMaxRange;
double CoarseMin;
double CoarseMax;
double CoarseRange;
double CoarseSubPixIts;
bool DisableCoarse;
double CoarseMinVelocity;
double TrackingQualityGood;
double TrackingQualityLost;
int TrackingQualityFoundPixels;
double MaxIterations;
int MaxKF;
std::string BundleMethod;
double UpdateSquaredConvergenceLimit;
bool BundleDebugMessages;
std::string FASTMethod;
int Thres_lvl0;
int Thres_lvl1;
int Thres_lvl2;
int Thres_lvl3;
bool AdaptiveThrs;
double AdaptiveThrsMult;
double RotationEstimatorBlur;
bool UseRotationEstimator;
int MiniPatchMaxSSD;
int PlaneAlignerRansacs;
int RelocMaxScore;
bool AutoInit;
bool CheckInitMapVar;
int AutoInitPixel;
int MaxStereoInitLoops;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double Scale;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string MotionModelSource;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MaxPatchesPerFrame;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MaxKFDistWiggleMult;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool UseKFPixelDist;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool NoLevelZeroMapPoints;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double EpiDepthSearchMaxRange;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double CoarseMin;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double CoarseMax;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double CoarseRange;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double CoarseSubPixIts;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool DisableCoarse;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double CoarseMinVelocity;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double TrackingQualityGood;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double TrackingQualityLost;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int TrackingQualityFoundPixels;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MaxIterations;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int MaxKF;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string BundleMethod;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double UpdateSquaredConvergenceLimit;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool BundleDebugMessages;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string FASTMethod;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Thres_lvl0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Thres_lvl1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Thres_lvl2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Thres_lvl3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool AdaptiveThrs;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double AdaptiveThrsMult;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double RotationEstimatorBlur;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool UseRotationEstimator;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int MiniPatchMaxSSD;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int PlaneAlignerRansacs;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int RelocMaxScore;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool AutoInit;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool CheckInitMapVar;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AutoInitPixel;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int MaxStereoInitLoops;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PtamParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PtamParamsConfig &__max__ = __getMax__();
      const PtamParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PtamParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PtamParamsConfig &__getDefault__();
    static const PtamParamsConfig &__getMax__();
    static const PtamParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PtamParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PtamParamsConfig::ParamDescription<std::string>::clamp(PtamParamsConfig &config, const PtamParamsConfig &max, const PtamParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PtamParamsConfigStatics
  {
    friend class PtamParamsConfig;

    PtamParamsConfigStatics()
    {
PtamParamsConfig::GroupDescription<PtamParamsConfig::DEFAULT, PtamParamsConfig> Default("Default", "", 0, 0, true, &PtamParamsConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Scale = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Scale = 30.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Scale = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("Scale", "double", 0, "Scale", "", &PtamParamsConfig::Scale)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("Scale", "double", 0, "Scale", "", &PtamParamsConfig::Scale)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MotionModelSource = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MotionModelSource = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MotionModelSource = "CONSTANT";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<std::string>("MotionModelSource", "str", 0, "selects the source for the motion model.", "{'enum_description': 'An enum to set wich input to use for the motion model.', 'enum': [{'srcline': 28, 'description': 'use constant motion model.', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'CONSTANT', 'ctype': 'std::string', 'type': 'str', 'name': 'MM_CONSTANT'}, {'srcline': 29, 'description': 'use imu orientation for the motion model.', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'IMU', 'ctype': 'std::string', 'type': 'str', 'name': 'MM_IMU'}, {'srcline': 30, 'description': 'use full pose estimated externally for motion model.', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'FULL_POSE', 'ctype': 'std::string', 'type': 'str', 'name': 'MM_FULL_POSE'}]}", &PtamParamsConfig::MotionModelSource)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<std::string>("MotionModelSource", "str", 0, "selects the source for the motion model.", "{'enum_description': 'An enum to set wich input to use for the motion model.', 'enum': [{'srcline': 28, 'description': 'use constant motion model.', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'CONSTANT', 'ctype': 'std::string', 'type': 'str', 'name': 'MM_CONSTANT'}, {'srcline': 29, 'description': 'use imu orientation for the motion model.', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'IMU', 'ctype': 'std::string', 'type': 'str', 'name': 'MM_IMU'}, {'srcline': 30, 'description': 'use full pose estimated externally for motion model.', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'FULL_POSE', 'ctype': 'std::string', 'type': 'str', 'name': 'MM_FULL_POSE'}]}", &PtamParamsConfig::MotionModelSource)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MaxPatchesPerFrame = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MaxPatchesPerFrame = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MaxPatchesPerFrame = 500.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("MaxPatchesPerFrame", "double", 0, "max features per frame", "", &PtamParamsConfig::MaxPatchesPerFrame)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("MaxPatchesPerFrame", "double", 0, "max features per frame", "", &PtamParamsConfig::MaxPatchesPerFrame)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MaxKFDistWiggleMult = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MaxKFDistWiggleMult = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MaxKFDistWiggleMult = 3.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("MaxKFDistWiggleMult", "double", 0, "'distance' after which a new kf is requested", "", &PtamParamsConfig::MaxKFDistWiggleMult)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("MaxKFDistWiggleMult", "double", 0, "'distance' after which a new kf is requested", "", &PtamParamsConfig::MaxKFDistWiggleMult)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.UseKFPixelDist = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.UseKFPixelDist = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.UseKFPixelDist = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("UseKFPixelDist", "bool", 0, "use AutoInitPixel as new KF request criteria", "", &PtamParamsConfig::UseKFPixelDist)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("UseKFPixelDist", "bool", 0, "use AutoInitPixel as new KF request criteria", "", &PtamParamsConfig::UseKFPixelDist)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.NoLevelZeroMapPoints = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.NoLevelZeroMapPoints = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.NoLevelZeroMapPoints = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("NoLevelZeroMapPoints", "bool", 0, "do not add map points at level zero", "", &PtamParamsConfig::NoLevelZeroMapPoints)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("NoLevelZeroMapPoints", "bool", 0, "do not add map points at level zero", "", &PtamParamsConfig::NoLevelZeroMapPoints)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.EpiDepthSearchMaxRange = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.EpiDepthSearchMaxRange = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.EpiDepthSearchMaxRange = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("EpiDepthSearchMaxRange", "double", 0, "depth variance to search for features", "", &PtamParamsConfig::EpiDepthSearchMaxRange)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("EpiDepthSearchMaxRange", "double", 0, "depth variance to search for features", "", &PtamParamsConfig::EpiDepthSearchMaxRange)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.CoarseMin = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.CoarseMin = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.CoarseMin = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseMin", "double", 0, "min number of features for coarse tracking", "", &PtamParamsConfig::CoarseMin)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseMin", "double", 0, "min number of features for coarse tracking", "", &PtamParamsConfig::CoarseMin)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.CoarseMax = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.CoarseMax = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.CoarseMax = 60.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseMax", "double", 0, "max number of features for coarse tracking", "", &PtamParamsConfig::CoarseMax)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseMax", "double", 0, "max number of features for coarse tracking", "", &PtamParamsConfig::CoarseMax)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.CoarseRange = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.CoarseRange = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.CoarseRange = 30.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseRange", "double", 0, "Pixel search radius for coarse features", "", &PtamParamsConfig::CoarseRange)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseRange", "double", 0, "Pixel search radius for coarse features", "", &PtamParamsConfig::CoarseRange)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.CoarseSubPixIts = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.CoarseSubPixIts = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.CoarseSubPixIts = 8.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseSubPixIts", "double", 0, "coarse tracking sub-pixel iterations", "", &PtamParamsConfig::CoarseSubPixIts)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseSubPixIts", "double", 0, "coarse tracking sub-pixel iterations", "", &PtamParamsConfig::CoarseSubPixIts)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.DisableCoarse = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.DisableCoarse = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.DisableCoarse = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("DisableCoarse", "bool", 0, "enable/disable coarse tracking", "", &PtamParamsConfig::DisableCoarse)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("DisableCoarse", "bool", 0, "enable/disable coarse tracking", "", &PtamParamsConfig::DisableCoarse)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.CoarseMinVelocity = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.CoarseMinVelocity = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.CoarseMinVelocity = 0.006;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseMinVelocity", "double", 0, "speed above which coarse stage is used", "", &PtamParamsConfig::CoarseMinVelocity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("CoarseMinVelocity", "double", 0, "speed above which coarse stage is used", "", &PtamParamsConfig::CoarseMinVelocity)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.TrackingQualityGood = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.TrackingQualityGood = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.TrackingQualityGood = 0.3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("TrackingQualityGood", "double", 0, "min ratio features visible/features found for good tracking", "", &PtamParamsConfig::TrackingQualityGood)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("TrackingQualityGood", "double", 0, "min ratio features visible/features found for good tracking", "", &PtamParamsConfig::TrackingQualityGood)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.TrackingQualityLost = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.TrackingQualityLost = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.TrackingQualityLost = 0.13;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("TrackingQualityLost", "double", 0, "max ratio features visible/features found before lost", "", &PtamParamsConfig::TrackingQualityLost)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("TrackingQualityLost", "double", 0, "max ratio features visible/features found before lost", "", &PtamParamsConfig::TrackingQualityLost)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.TrackingQualityFoundPixels = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.TrackingQualityFoundPixels = 1000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.TrackingQualityFoundPixels = 100;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("TrackingQualityFoundPixels", "int", 0, "min pixels to be found for good tracking", "", &PtamParamsConfig::TrackingQualityFoundPixels)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("TrackingQualityFoundPixels", "int", 0, "min pixels to be found for good tracking", "", &PtamParamsConfig::TrackingQualityFoundPixels)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MaxIterations = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MaxIterations = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MaxIterations = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("MaxIterations", "double", 0, "max iterations for bundle adjustment", "", &PtamParamsConfig::MaxIterations)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("MaxIterations", "double", 0, "max iterations for bundle adjustment", "", &PtamParamsConfig::MaxIterations)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MaxKF = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MaxKF = 1000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MaxKF = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("MaxKF", "int", 0, "number of keyframes kept in the map (0 or 1 = inf)", "", &PtamParamsConfig::MaxKF)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("MaxKF", "int", 0, "number of keyframes kept in the map (0 or 1 = inf)", "", &PtamParamsConfig::MaxKF)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BundleMethod = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BundleMethod = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BundleMethod = "LOCAL_GLOBAL";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<std::string>("BundleMethod", "str", 0, "bundleadjustment method", "{'enum_description': 'An enum to set the bundle adjustment mode.', 'enum': [{'srcline': 14, 'description': 'local and global bundle adjustment', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'LOCAL_GLOBAL', 'ctype': 'std::string', 'type': 'str', 'name': 'LOCAL_GLOBAL'}, {'srcline': 15, 'description': 'local bundle adjustment only', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'LOCAL', 'ctype': 'std::string', 'type': 'str', 'name': 'LOCAL'}, {'srcline': 16, 'description': 'global bundle adjustment only', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'GLOBAL', 'ctype': 'std::string', 'type': 'str', 'name': 'GLOBAL'}]}", &PtamParamsConfig::BundleMethod)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<std::string>("BundleMethod", "str", 0, "bundleadjustment method", "{'enum_description': 'An enum to set the bundle adjustment mode.', 'enum': [{'srcline': 14, 'description': 'local and global bundle adjustment', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'LOCAL_GLOBAL', 'ctype': 'std::string', 'type': 'str', 'name': 'LOCAL_GLOBAL'}, {'srcline': 15, 'description': 'local bundle adjustment only', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'LOCAL', 'ctype': 'std::string', 'type': 'str', 'name': 'LOCAL'}, {'srcline': 16, 'description': 'global bundle adjustment only', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'GLOBAL', 'ctype': 'std::string', 'type': 'str', 'name': 'GLOBAL'}]}", &PtamParamsConfig::BundleMethod)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.UpdateSquaredConvergenceLimit = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.UpdateSquaredConvergenceLimit = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.UpdateSquaredConvergenceLimit = 1e-06;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("UpdateSquaredConvergenceLimit", "double", 0, "limit for convergence in bundle adjustment", "", &PtamParamsConfig::UpdateSquaredConvergenceLimit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("UpdateSquaredConvergenceLimit", "double", 0, "limit for convergence in bundle adjustment", "", &PtamParamsConfig::UpdateSquaredConvergenceLimit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BundleDebugMessages = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BundleDebugMessages = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BundleDebugMessages = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("BundleDebugMessages", "bool", 0, "print bundle debug messages", "", &PtamParamsConfig::BundleDebugMessages)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("BundleDebugMessages", "bool", 0, "print bundle debug messages", "", &PtamParamsConfig::BundleDebugMessages)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FASTMethod = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FASTMethod = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FASTMethod = "FAST9_nonmax";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<std::string>("FASTMethod", "str", 0, "FAST corner method", "{'enum_description': 'An enum to set the FAST corner extraction method.', 'enum': [{'srcline': 20, 'description': 'FAST 9', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST9', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST9'}, {'srcline': 21, 'description': 'FAST 10', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST10', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST10'}, {'srcline': 22, 'description': 'FAST 9 with nonmax suppression', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST9_nonmax', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST9_nonmax'}, {'srcline': 23, 'description': 'AGAST 12 pixel diamond', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'AGAST12d', 'ctype': 'std::string', 'type': 'str', 'name': 'AGAST12d'}, {'srcline': 24, 'description': 'AGAST 16 pixel circular', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'OAST16', 'ctype': 'std::string', 'type': 'str', 'name': 'OAST16'}]}", &PtamParamsConfig::FASTMethod)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<std::string>("FASTMethod", "str", 0, "FAST corner method", "{'enum_description': 'An enum to set the FAST corner extraction method.', 'enum': [{'srcline': 20, 'description': 'FAST 9', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST9', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST9'}, {'srcline': 21, 'description': 'FAST 10', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST10', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST10'}, {'srcline': 22, 'description': 'FAST 9 with nonmax suppression', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'FAST9_nonmax', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST9_nonmax'}, {'srcline': 23, 'description': 'AGAST 12 pixel diamond', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'AGAST12d', 'ctype': 'std::string', 'type': 'str', 'name': 'AGAST12d'}, {'srcline': 24, 'description': 'AGAST 16 pixel circular', 'srcfile': '/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg', 'cconsttype': 'const char * const', 'value': 'OAST16', 'ctype': 'std::string', 'type': 'str', 'name': 'OAST16'}]}", &PtamParamsConfig::FASTMethod)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Thres_lvl0 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Thres_lvl0 = 255;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Thres_lvl0 = 10;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("Thres_lvl0", "int", 0, "threshold for FAST features on level 0", "", &PtamParamsConfig::Thres_lvl0)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("Thres_lvl0", "int", 0, "threshold for FAST features on level 0", "", &PtamParamsConfig::Thres_lvl0)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Thres_lvl1 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Thres_lvl1 = 255;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Thres_lvl1 = 15;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("Thres_lvl1", "int", 0, "threshold for FAST features on level 1", "", &PtamParamsConfig::Thres_lvl1)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("Thres_lvl1", "int", 0, "threshold for FAST features on level 1", "", &PtamParamsConfig::Thres_lvl1)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Thres_lvl2 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Thres_lvl2 = 255;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Thres_lvl2 = 15;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("Thres_lvl2", "int", 0, "threshold for FAST features on level 2", "", &PtamParamsConfig::Thres_lvl2)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("Thres_lvl2", "int", 0, "threshold for FAST features on level 2", "", &PtamParamsConfig::Thres_lvl2)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Thres_lvl3 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Thres_lvl3 = 255;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Thres_lvl3 = 10;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("Thres_lvl3", "int", 0, "threshold for FAST features on level 3", "", &PtamParamsConfig::Thres_lvl3)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("Thres_lvl3", "int", 0, "threshold for FAST features on level 3", "", &PtamParamsConfig::Thres_lvl3)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AdaptiveThrs = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AdaptiveThrs = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AdaptiveThrs = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("AdaptiveThrs", "bool", 0, "adaptive threshold for corner extraction", "", &PtamParamsConfig::AdaptiveThrs)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("AdaptiveThrs", "bool", 0, "adaptive threshold for corner extraction", "", &PtamParamsConfig::AdaptiveThrs)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AdaptiveThrsMult = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AdaptiveThrsMult = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AdaptiveThrsMult = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("AdaptiveThrsMult", "double", 0, "controls adaptive threshold to MaxPatches*N corners", "", &PtamParamsConfig::AdaptiveThrsMult)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("AdaptiveThrsMult", "double", 0, "controls adaptive threshold to MaxPatches*N corners", "", &PtamParamsConfig::AdaptiveThrsMult)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.RotationEstimatorBlur = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.RotationEstimatorBlur = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.RotationEstimatorBlur = 0.75;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("RotationEstimatorBlur", "double", 0, "small images for the rotation estimator blur", "", &PtamParamsConfig::RotationEstimatorBlur)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<double>("RotationEstimatorBlur", "double", 0, "small images for the rotation estimator blur", "", &PtamParamsConfig::RotationEstimatorBlur)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.UseRotationEstimator = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.UseRotationEstimator = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.UseRotationEstimator = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("UseRotationEstimator", "bool", 0, "small images for the rotation estimator enable/disable", "", &PtamParamsConfig::UseRotationEstimator)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("UseRotationEstimator", "bool", 0, "small images for the rotation estimator enable/disable", "", &PtamParamsConfig::UseRotationEstimator)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MiniPatchMaxSSD = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MiniPatchMaxSSD = 10000000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MiniPatchMaxSSD = 100000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("MiniPatchMaxSSD", "int", 0, "MiniPatch tracking threshhold", "", &PtamParamsConfig::MiniPatchMaxSSD)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("MiniPatchMaxSSD", "int", 0, "MiniPatch tracking threshhold", "", &PtamParamsConfig::MiniPatchMaxSSD)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.PlaneAlignerRansacs = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.PlaneAlignerRansacs = 1000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.PlaneAlignerRansacs = 100;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("PlaneAlignerRansacs", "int", 0, "number of dominant plane RANSACs", "", &PtamParamsConfig::PlaneAlignerRansacs)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("PlaneAlignerRansacs", "int", 0, "number of dominant plane RANSACs", "", &PtamParamsConfig::PlaneAlignerRansacs)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.RelocMaxScore = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.RelocMaxScore = 90000000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.RelocMaxScore = 9000000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("RelocMaxScore", "int", 0, "score for relocalization", "", &PtamParamsConfig::RelocMaxScore)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("RelocMaxScore", "int", 0, "score for relocalization", "", &PtamParamsConfig::RelocMaxScore)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AutoInit = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AutoInit = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AutoInit = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("AutoInit", "bool", 0, "enable auto initialization", "", &PtamParamsConfig::AutoInit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("AutoInit", "bool", 0, "enable auto initialization", "", &PtamParamsConfig::AutoInit)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.CheckInitMapVar = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.CheckInitMapVar = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.CheckInitMapVar = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("CheckInitMapVar", "bool", 0, "check map point variance for initial map", "", &PtamParamsConfig::CheckInitMapVar)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<bool>("CheckInitMapVar", "bool", 0, "check map point variance for initial map", "", &PtamParamsConfig::CheckInitMapVar)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AutoInitPixel = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AutoInitPixel = 100;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AutoInitPixel = 20;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("AutoInitPixel", "int", 0, "min pixel distance for auto initialization", "", &PtamParamsConfig::AutoInitPixel)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("AutoInitPixel", "int", 0, "min pixel distance for auto initialization", "", &PtamParamsConfig::AutoInitPixel)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MaxStereoInitLoops = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MaxStereoInitLoops = 100;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MaxStereoInitLoops = 10;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("MaxStereoInitLoops", "int", 0, "max # of loops for stereo initialization", "", &PtamParamsConfig::MaxStereoInitLoops)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PtamParamsConfig::AbstractParamDescriptionConstPtr(new PtamParamsConfig::ParamDescription<int>("MaxStereoInitLoops", "int", 0, "max # of loops for stereo initialization", "", &PtamParamsConfig::MaxStereoInitLoops)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PtamParamsConfig::AbstractGroupDescriptionConstPtr(new PtamParamsConfig::GroupDescription<PtamParamsConfig::DEFAULT, PtamParamsConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PtamParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PtamParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PtamParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PtamParamsConfig __max__;
    PtamParamsConfig __min__;
    PtamParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PtamParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PtamParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PtamParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PtamParamsConfig &PtamParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PtamParamsConfig &PtamParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PtamParamsConfig &PtamParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PtamParamsConfig::AbstractParamDescriptionConstPtr> &PtamParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PtamParamsConfig::AbstractGroupDescriptionConstPtr> &PtamParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PtamParamsConfigStatics *PtamParamsConfig::__get_statics__()
  {
    const static PtamParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PtamParamsConfigStatics::get_instance();

    return statics;
  }

//#line 14 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_LOCAL_GLOBAL = "LOCAL_GLOBAL";
//#line 15 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_LOCAL = "LOCAL";
//#line 16 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_GLOBAL = "GLOBAL";
//#line 20 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_FAST9 = "FAST9";
//#line 21 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_FAST10 = "FAST10";
//#line 22 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_FAST9_nonmax = "FAST9_nonmax";
//#line 23 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_AGAST12d = "AGAST12d";
//#line 24 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_OAST16 = "OAST16";
//#line 28 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_MM_CONSTANT = "CONSTANT";
//#line 29 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_MM_IMU = "IMU";
//#line 30 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const char * const PtamParams_MM_FULL_POSE = "FULL_POSE";
//#line 33 "/home/tongjirc/catkin_ws/src/ethzasl_ptam/ptam/cfg/PtamParams.cfg"
      const int PtamParams_SEND_PARAMETERS = 1;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PTAMPARAMSRECONFIGURATOR_H__
