// Generated by gencpp from file ptam_com/KeyFrame_srv.msg
// DO NOT EDIT!


#ifndef PTAM_COM_MESSAGE_KEYFRAME_SRV_H
#define PTAM_COM_MESSAGE_KEYFRAME_SRV_H

#include <ros/service_traits.h>


#include <ptam_com/KeyFrame_srvRequest.h>
#include <ptam_com/KeyFrame_srvResponse.h>


namespace ptam_com
{

struct KeyFrame_srv
{

typedef KeyFrame_srvRequest Request;
typedef KeyFrame_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KeyFrame_srv
} // namespace ptam_com


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ptam_com::KeyFrame_srv > {
  static const char* value()
  {
    return "1950b962db053cd38d36594521dda474";
  }

  static const char* value(const ::ptam_com::KeyFrame_srv&) { return value(); }
};

template<>
struct DataType< ::ptam_com::KeyFrame_srv > {
  static const char* value()
  {
    return "ptam_com/KeyFrame_srv";
  }

  static const char* value(const ::ptam_com::KeyFrame_srv&) { return value(); }
};


// service_traits::MD5Sum< ::ptam_com::KeyFrame_srvRequest> should match 
// service_traits::MD5Sum< ::ptam_com::KeyFrame_srv > 
template<>
struct MD5Sum< ::ptam_com::KeyFrame_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ptam_com::KeyFrame_srv >::value();
  }
  static const char* value(const ::ptam_com::KeyFrame_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ptam_com::KeyFrame_srvRequest> should match 
// service_traits::DataType< ::ptam_com::KeyFrame_srv > 
template<>
struct DataType< ::ptam_com::KeyFrame_srvRequest>
{
  static const char* value()
  {
    return DataType< ::ptam_com::KeyFrame_srv >::value();
  }
  static const char* value(const ::ptam_com::KeyFrame_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ptam_com::KeyFrame_srvResponse> should match 
// service_traits::MD5Sum< ::ptam_com::KeyFrame_srv > 
template<>
struct MD5Sum< ::ptam_com::KeyFrame_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ptam_com::KeyFrame_srv >::value();
  }
  static const char* value(const ::ptam_com::KeyFrame_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ptam_com::KeyFrame_srvResponse> should match 
// service_traits::DataType< ::ptam_com::KeyFrame_srv > 
template<>
struct DataType< ::ptam_com::KeyFrame_srvResponse>
{
  static const char* value()
  {
    return DataType< ::ptam_com::KeyFrame_srv >::value();
  }
  static const char* value(const ::ptam_com::KeyFrame_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PTAM_COM_MESSAGE_KEYFRAME_SRV_H
