# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from marvelmind_nav/hedge_pos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class hedge_pos(genpy.Message):
  _md5sum = "5d7dc3e9efe3ead353f74615346c8145"
  _type = "marvelmind_nav/hedge_pos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 timestamp_ms
float64 x_m
float64 y_m
float64 z_m
uint8 flags
"""
  __slots__ = ['timestamp_ms','x_m','y_m','z_m','flags']
  _slot_types = ['int64','float64','float64','float64','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp_ms,x_m,y_m,z_m,flags

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(hedge_pos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp_ms is None:
        self.timestamp_ms = 0
      if self.x_m is None:
        self.x_m = 0.
      if self.y_m is None:
        self.y_m = 0.
      if self.z_m is None:
        self.z_m = 0.
      if self.flags is None:
        self.flags = 0
    else:
      self.timestamp_ms = 0
      self.x_m = 0.
      self.y_m = 0.
      self.z_m = 0.
      self.flags = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q3dB().pack(_x.timestamp_ms, _x.x_m, _x.y_m, _x.z_m, _x.flags))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.timestamp_ms, _x.x_m, _x.y_m, _x.z_m, _x.flags,) = _get_struct_q3dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q3dB().pack(_x.timestamp_ms, _x.x_m, _x.y_m, _x.z_m, _x.flags))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.timestamp_ms, _x.x_m, _x.y_m, _x.z_m, _x.flags,) = _get_struct_q3dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q3dB = None
def _get_struct_q3dB():
    global _struct_q3dB
    if _struct_q3dB is None:
        _struct_q3dB = struct.Struct("<q3dB")
    return _struct_q3dB
