(cl:in-package marvelmind_nav-msg)
(cl:export '(TIMESTAMP_MS-VAL
          TIMESTAMP_MS
          X_M-VAL
          X_M
          Y_M-VAL
          Y_M
          Z_M-VAL
          Z_M
          QW-VAL
          QW
          QX-VAL
          QX
          QY-VAL
          QY
          QZ-VAL
          QZ
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
))