(cl:defpackage tongjirc-msg
  (:use )
  (:export
   "<TONGJIRCACTION>"
   "TONGJIRCACTION"
   "<TONGJIRCACTIONFEEDBACK>"
   "TONGJIRCACTIONFEEDBACK"
   "<TONGJIRCACTIONGOAL>"
   "TONGJIRCACTIONGOAL"
   "<TONGJIRCACTIONRESULT>"
   "TONGJIRCACTIONRESULT"
   "<TONGJIRCFEEDBACK>"
   "TONGJIRCFEEDBACK"
   "<TONGJIRCGOAL>"
   "TONGJIRCGOAL"
   "<TONGJIRCRESULT>"
   "TONGJIRCRESULT"
  ))

