; Auto-generated. Do not edit!


(cl:in-package tongjirc-msg)


;//! \htmlinclude tongjircGoal.msg.html

(cl:defclass <tongjircGoal> (roslisp-msg-protocol:ros-message)
  ((dishwasher_id
    :reader dishwasher_id
    :initarg :dishwasher_id
    :type cl:integer
    :initform 0))
)

(cl:defclass tongjircGoal (<tongjircGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <tongjircGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'tongjircGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tongjirc-msg:<tongjircGoal> is deprecated: use tongjirc-msg:tongjircGoal instead.")))

(cl:ensure-generic-function 'dishwasher_id-val :lambda-list '(m))
(cl:defmethod dishwasher_id-val ((m <tongjircGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tongjirc-msg:dishwasher_id-val is deprecated.  Use tongjirc-msg:dishwasher_id instead.")
  (dishwasher_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <tongjircGoal>) ostream)
  "Serializes a message object of type '<tongjircGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dishwasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'dishwasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'dishwasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'dishwasher_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <tongjircGoal>) istream)
  "Deserializes a message object of type '<tongjircGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<tongjircGoal>)))
  "Returns string type for a message object of type '<tongjircGoal>"
  "tongjirc/tongjircGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'tongjircGoal)))
  "Returns string type for a message object of type 'tongjircGoal"
  "tongjirc/tongjircGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<tongjircGoal>)))
  "Returns md5sum for a message object of type '<tongjircGoal>"
  "65bd9e09a531006f4ecdeabe719004b9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'tongjircGoal)))
  "Returns md5sum for a message object of type 'tongjircGoal"
  "65bd9e09a531006f4ecdeabe719004b9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<tongjircGoal>)))
  "Returns full string definition for message of type '<tongjircGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 dishwasher_id  # Specify which dishwasher we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'tongjircGoal)))
  "Returns full string definition for message of type 'tongjircGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 dishwasher_id  # Specify which dishwasher we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <tongjircGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <tongjircGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'tongjircGoal
    (cl:cons ':dishwasher_id (dishwasher_id msg))
))
