; Auto-generated. Do not edit!


(cl:in-package tongjirc-msg)


;//! \htmlinclude tongjircResult.msg.html

(cl:defclass <tongjircResult> (roslisp-msg-protocol:ros-message)
  ((total_dishes_cleaned
    :reader total_dishes_cleaned
    :initarg :total_dishes_cleaned
    :type cl:integer
    :initform 0))
)

(cl:defclass tongjircResult (<tongjircResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <tongjircResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'tongjircResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tongjirc-msg:<tongjircResult> is deprecated: use tongjirc-msg:tongjircResult instead.")))

(cl:ensure-generic-function 'total_dishes_cleaned-val :lambda-list '(m))
(cl:defmethod total_dishes_cleaned-val ((m <tongjircResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tongjirc-msg:total_dishes_cleaned-val is deprecated.  Use tongjirc-msg:total_dishes_cleaned instead.")
  (total_dishes_cleaned m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <tongjircResult>) ostream)
  "Serializes a message object of type '<tongjircResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <tongjircResult>) istream)
  "Deserializes a message object of type '<tongjircResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<tongjircResult>)))
  "Returns string type for a message object of type '<tongjircResult>"
  "tongjirc/tongjircResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'tongjircResult)))
  "Returns string type for a message object of type 'tongjircResult"
  "tongjirc/tongjircResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<tongjircResult>)))
  "Returns md5sum for a message object of type '<tongjircResult>"
  "58faa44dda59c6545bea63ff57491cbe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'tongjircResult)))
  "Returns md5sum for a message object of type 'tongjircResult"
  "58faa44dda59c6545bea63ff57491cbe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<tongjircResult>)))
  "Returns full string definition for message of type '<tongjircResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'tongjircResult)))
  "Returns full string definition for message of type 'tongjircResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <tongjircResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <tongjircResult>))
  "Converts a ROS message object to a list"
  (cl:list 'tongjircResult
    (cl:cons ':total_dishes_cleaned (total_dishes_cleaned msg))
))
