// Generated by gencpp from file output/output.msg
// DO NOT EDIT!


#ifndef OUTPUT_MESSAGE_OUTPUT_H
#define OUTPUT_MESSAGE_OUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace output
{
template <class ContainerAllocator>
struct output_
{
  typedef output_<ContainerAllocator> Type;

  output_()
    : state(0)
    , motor(0.0)
    , steer(0.0)  {
    }
  output_(const ContainerAllocator& _alloc)
    : state(0)
    , motor(0.0)
    , steer(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _state_type;
  _state_type state;

   typedef double _motor_type;
  _motor_type motor;

   typedef double _steer_type;
  _steer_type steer;





  typedef boost::shared_ptr< ::output::output_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::output::output_<ContainerAllocator> const> ConstPtr;

}; // struct output_

typedef ::output::output_<std::allocator<void> > output;

typedef boost::shared_ptr< ::output::output > outputPtr;
typedef boost::shared_ptr< ::output::output const> outputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::output::output_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::output::output_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace output

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'output': ['/home/tongjirc/catkin_ws/src/output/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::output::output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::output::output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::output::output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::output::output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::output::output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::output::output_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::output::output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e65caaa63c403a0af0f3267ca901c242";
  }

  static const char* value(const ::output::output_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe65caaa63c403a0aULL;
  static const uint64_t static_value2 = 0xf0f3267ca901c242ULL;
};

template<class ContainerAllocator>
struct DataType< ::output::output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "output/output";
  }

  static const char* value(const ::output::output_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::output::output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 state\n\
float64 motor\n\
float64 steer\n\
";
  }

  static const char* value(const ::output::output_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::output::output_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.motor);
      stream.next(m.steer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct output_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::output::output_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::output::output_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "motor: ";
    Printer<double>::stream(s, indent + "  ", v.motor);
    s << indent << "steer: ";
    Printer<double>::stream(s, indent + "  ", v.steer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OUTPUT_MESSAGE_OUTPUT_H
