// Generated by gencpp from file YOLO/YOLO.msg
// DO NOT EDIT!


#ifndef YOLO_MESSAGE_YOLO_H
#define YOLO_MESSAGE_YOLO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace YOLO
{
template <class ContainerAllocator>
struct YOLO_
{
  typedef YOLO_<ContainerAllocator> Type;

  YOLO_()
    : header()
    , classIds()
    , confidences()
    , boxes4()  {
    }
  YOLO_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , classIds(_alloc)
    , confidences(_alloc)
    , boxes4(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _classIds_type;
  _classIds_type classIds;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _confidences_type;
  _confidences_type confidences;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _boxes4_type;
  _boxes4_type boxes4;





  typedef boost::shared_ptr< ::YOLO::YOLO_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::YOLO::YOLO_<ContainerAllocator> const> ConstPtr;

}; // struct YOLO_

typedef ::YOLO::YOLO_<std::allocator<void> > YOLO;

typedef boost::shared_ptr< ::YOLO::YOLO > YOLOPtr;
typedef boost::shared_ptr< ::YOLO::YOLO const> YOLOConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::YOLO::YOLO_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::YOLO::YOLO_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace YOLO

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'YOLO': ['/home/tongjirc/catkin_ws/src/YOLO/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::YOLO::YOLO_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::YOLO::YOLO_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::YOLO::YOLO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::YOLO::YOLO_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::YOLO::YOLO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::YOLO::YOLO_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::YOLO::YOLO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71d52b23e2f4848dfc8e90e1502e429b";
  }

  static const char* value(const ::YOLO::YOLO_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71d52b23e2f4848dULL;
  static const uint64_t static_value2 = 0xfc8e90e1502e429bULL;
};

template<class ContainerAllocator>
struct DataType< ::YOLO::YOLO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "YOLO/YOLO";
  }

  static const char* value(const ::YOLO::YOLO_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::YOLO::YOLO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
std_msgs/Header header\n\
\n\
#classIds,confidences,boxes(left, top, width, height)\n\
\n\
float64[] classIds\n\
float64[] confidences\n\
#boxes.flat()\n\
uint8[] boxes4\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::YOLO::YOLO_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::YOLO::YOLO_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.classIds);
      stream.next(m.confidences);
      stream.next(m.boxes4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YOLO_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::YOLO::YOLO_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::YOLO::YOLO_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "classIds[]" << std::endl;
    for (size_t i = 0; i < v.classIds.size(); ++i)
    {
      s << indent << "  classIds[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.classIds[i]);
    }
    s << indent << "confidences[]" << std::endl;
    for (size_t i = 0; i < v.confidences.size(); ++i)
    {
      s << indent << "  confidences[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.confidences[i]);
    }
    s << indent << "boxes4[]" << std::endl;
    for (size_t i = 0; i < v.boxes4.size(); ++i)
    {
      s << indent << "  boxes4[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.boxes4[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_MESSAGE_YOLO_H
