// Generated by gencpp from file ptam_com/PointCloud.msg
// DO NOT EDIT!


#ifndef PTAM_COM_MESSAGE_POINTCLOUD_H
#define PTAM_COM_MESSAGE_POINTCLOUD_H

#include <ros/service_traits.h>


#include <ptam_com/PointCloudRequest.h>
#include <ptam_com/PointCloudResponse.h>


namespace ptam_com
{

struct PointCloud
{

typedef PointCloudRequest Request;
typedef PointCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PointCloud
} // namespace ptam_com


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ptam_com::PointCloud > {
  static const char* value()
  {
    return "5f22ae501f068f11fc397cb230046acc";
  }

  static const char* value(const ::ptam_com::PointCloud&) { return value(); }
};

template<>
struct DataType< ::ptam_com::PointCloud > {
  static const char* value()
  {
    return "ptam_com/PointCloud";
  }

  static const char* value(const ::ptam_com::PointCloud&) { return value(); }
};


// service_traits::MD5Sum< ::ptam_com::PointCloudRequest> should match 
// service_traits::MD5Sum< ::ptam_com::PointCloud > 
template<>
struct MD5Sum< ::ptam_com::PointCloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ptam_com::PointCloud >::value();
  }
  static const char* value(const ::ptam_com::PointCloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ptam_com::PointCloudRequest> should match 
// service_traits::DataType< ::ptam_com::PointCloud > 
template<>
struct DataType< ::ptam_com::PointCloudRequest>
{
  static const char* value()
  {
    return DataType< ::ptam_com::PointCloud >::value();
  }
  static const char* value(const ::ptam_com::PointCloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ptam_com::PointCloudResponse> should match 
// service_traits::MD5Sum< ::ptam_com::PointCloud > 
template<>
struct MD5Sum< ::ptam_com::PointCloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ptam_com::PointCloud >::value();
  }
  static const char* value(const ::ptam_com::PointCloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ptam_com::PointCloudResponse> should match 
// service_traits::DataType< ::ptam_com::PointCloud > 
template<>
struct DataType< ::ptam_com::PointCloudResponse>
{
  static const char* value()
  {
    return DataType< ::ptam_com::PointCloud >::value();
  }
  static const char* value(const ::ptam_com::PointCloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PTAM_COM_MESSAGE_POINTCLOUD_H
