// Generated by gencpp from file tongjirc/tongjircFeedback.msg
// DO NOT EDIT!


#ifndef TONGJIRC_MESSAGE_TONGJIRCFEEDBACK_H
#define TONGJIRC_MESSAGE_TONGJIRCFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tongjirc
{
template <class ContainerAllocator>
struct tongjircFeedback_
{
  typedef tongjircFeedback_<ContainerAllocator> Type;

  tongjircFeedback_()
    : percent_completes(0.0)  {
    }
  tongjircFeedback_(const ContainerAllocator& _alloc)
    : percent_completes(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_completes_type;
  _percent_completes_type percent_completes;





  typedef boost::shared_ptr< ::tongjirc::tongjircFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tongjirc::tongjircFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct tongjircFeedback_

typedef ::tongjirc::tongjircFeedback_<std::allocator<void> > tongjircFeedback;

typedef boost::shared_ptr< ::tongjirc::tongjircFeedback > tongjircFeedbackPtr;
typedef boost::shared_ptr< ::tongjirc::tongjircFeedback const> tongjircFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tongjirc::tongjircFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tongjirc::tongjircFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tongjirc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'tongjirc': ['/home/tongjirc/catkin_ws/devel/share/tongjirc/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tongjirc::tongjircFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tongjirc::tongjircFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tongjirc::tongjircFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tongjirc::tongjircFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tongjirc::tongjircFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tongjirc::tongjircFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tongjirc::tongjircFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b348798990ac2df8ee8319c093eab504";
  }

  static const char* value(const ::tongjirc::tongjircFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb348798990ac2df8ULL;
  static const uint64_t static_value2 = 0xee8319c093eab504ULL;
};

template<class ContainerAllocator>
struct DataType< ::tongjirc::tongjircFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tongjirc/tongjircFeedback";
  }

  static const char* value(const ::tongjirc::tongjircFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tongjirc::tongjircFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message \n\
float32 percent_completes\n\
";
  }

  static const char* value(const ::tongjirc::tongjircFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tongjirc::tongjircFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_completes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tongjircFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tongjirc::tongjircFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tongjirc::tongjircFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_completes: ";
    Printer<float>::stream(s, indent + "  ", v.percent_completes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TONGJIRC_MESSAGE_TONGJIRCFEEDBACK_H
