// Generated by gencpp from file tongjirc/rcinput.msg
// DO NOT EDIT!


#ifndef TONGJIRC_MESSAGE_RCINPUT_H
#define TONGJIRC_MESSAGE_RCINPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tongjirc
{
template <class ContainerAllocator>
struct rcinput_
{
  typedef rcinput_<ContainerAllocator> Type;

  rcinput_()
    : EngineInput(0)
    , SteerInput(0)  {
    }
  rcinput_(const ContainerAllocator& _alloc)
    : EngineInput(0)
    , SteerInput(0)  {
  (void)_alloc;
    }



   typedef int64_t _EngineInput_type;
  _EngineInput_type EngineInput;

   typedef int64_t _SteerInput_type;
  _SteerInput_type SteerInput;





  typedef boost::shared_ptr< ::tongjirc::rcinput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tongjirc::rcinput_<ContainerAllocator> const> ConstPtr;

}; // struct rcinput_

typedef ::tongjirc::rcinput_<std::allocator<void> > rcinput;

typedef boost::shared_ptr< ::tongjirc::rcinput > rcinputPtr;
typedef boost::shared_ptr< ::tongjirc::rcinput const> rcinputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tongjirc::rcinput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tongjirc::rcinput_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tongjirc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tongjirc': ['/home/tongjirc/catkin_ws/src/tongjirc/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tongjirc::rcinput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tongjirc::rcinput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tongjirc::rcinput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tongjirc::rcinput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tongjirc::rcinput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tongjirc::rcinput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tongjirc::rcinput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8fc30fb11cc0f978b5dd3ea0ef06177";
  }

  static const char* value(const ::tongjirc::rcinput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8fc30fb11cc0f97ULL;
  static const uint64_t static_value2 = 0x8b5dd3ea0ef06177ULL;
};

template<class ContainerAllocator>
struct DataType< ::tongjirc::rcinput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tongjirc/rcinput";
  }

  static const char* value(const ::tongjirc::rcinput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tongjirc::rcinput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 EngineInput\n\
int64 SteerInput\n\
";
  }

  static const char* value(const ::tongjirc::rcinput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tongjirc::rcinput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.EngineInput);
      stream.next(m.SteerInput);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rcinput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tongjirc::rcinput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tongjirc::rcinput_<ContainerAllocator>& v)
  {
    s << indent << "EngineInput: ";
    Printer<int64_t>::stream(s, indent + "  ", v.EngineInput);
    s << indent << "SteerInput: ";
    Printer<int64_t>::stream(s, indent + "  ", v.SteerInput);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TONGJIRC_MESSAGE_RCINPUT_H
