// Generated by gencpp from file tongjirc/tongjircResult.msg
// DO NOT EDIT!


#ifndef TONGJIRC_MESSAGE_TONGJIRCRESULT_H
#define TONGJIRC_MESSAGE_TONGJIRCRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tongjirc
{
template <class ContainerAllocator>
struct tongjircResult_
{
  typedef tongjircResult_<ContainerAllocator> Type;

  tongjircResult_()
    : total_dishes_cleaned(0)  {
    }
  tongjircResult_(const ContainerAllocator& _alloc)
    : total_dishes_cleaned(0)  {
  (void)_alloc;
    }



   typedef uint32_t _total_dishes_cleaned_type;
  _total_dishes_cleaned_type total_dishes_cleaned;





  typedef boost::shared_ptr< ::tongjirc::tongjircResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tongjirc::tongjircResult_<ContainerAllocator> const> ConstPtr;

}; // struct tongjircResult_

typedef ::tongjirc::tongjircResult_<std::allocator<void> > tongjircResult;

typedef boost::shared_ptr< ::tongjirc::tongjircResult > tongjircResultPtr;
typedef boost::shared_ptr< ::tongjirc::tongjircResult const> tongjircResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tongjirc::tongjircResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tongjirc::tongjircResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tongjirc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'tongjirc': ['/home/tongjirc/catkin_ws/devel/share/tongjirc/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tongjirc::tongjircResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tongjirc::tongjircResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tongjirc::tongjircResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tongjirc::tongjircResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tongjirc::tongjircResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tongjirc::tongjircResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tongjirc::tongjircResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58faa44dda59c6545bea63ff57491cbe";
  }

  static const char* value(const ::tongjirc::tongjircResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58faa44dda59c654ULL;
  static const uint64_t static_value2 = 0x5bea63ff57491cbeULL;
};

template<class ContainerAllocator>
struct DataType< ::tongjirc::tongjircResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tongjirc/tongjircResult";
  }

  static const char* value(const ::tongjirc::tongjircResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tongjirc::tongjircResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
uint32 total_dishes_cleaned\n\
";
  }

  static const char* value(const ::tongjirc::tongjircResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tongjirc::tongjircResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_dishes_cleaned);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tongjircResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tongjirc::tongjircResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tongjirc::tongjircResult_<ContainerAllocator>& v)
  {
    s << indent << "total_dishes_cleaned: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_dishes_cleaned);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TONGJIRC_MESSAGE_TONGJIRCRESULT_H
