// Generated by gencpp from file tongjirc/tongjircGoal.msg
// DO NOT EDIT!


#ifndef TONGJIRC_MESSAGE_TONGJIRCGOAL_H
#define TONGJIRC_MESSAGE_TONGJIRCGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tongjirc
{
template <class ContainerAllocator>
struct tongjircGoal_
{
  typedef tongjircGoal_<ContainerAllocator> Type;

  tongjircGoal_()
    : dishwasher_id(0)  {
    }
  tongjircGoal_(const ContainerAllocator& _alloc)
    : dishwasher_id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _dishwasher_id_type;
  _dishwasher_id_type dishwasher_id;





  typedef boost::shared_ptr< ::tongjirc::tongjircGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tongjirc::tongjircGoal_<ContainerAllocator> const> ConstPtr;

}; // struct tongjircGoal_

typedef ::tongjirc::tongjircGoal_<std::allocator<void> > tongjircGoal;

typedef boost::shared_ptr< ::tongjirc::tongjircGoal > tongjircGoalPtr;
typedef boost::shared_ptr< ::tongjirc::tongjircGoal const> tongjircGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tongjirc::tongjircGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tongjirc::tongjircGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tongjirc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'tongjirc': ['/home/tongjirc/catkin_ws/devel/share/tongjirc/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tongjirc::tongjircGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tongjirc::tongjircGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tongjirc::tongjircGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tongjirc::tongjircGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tongjirc::tongjircGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tongjirc::tongjircGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tongjirc::tongjircGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65bd9e09a531006f4ecdeabe719004b9";
  }

  static const char* value(const ::tongjirc::tongjircGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65bd9e09a531006fULL;
  static const uint64_t static_value2 = 0x4ecdeabe719004b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::tongjirc::tongjircGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tongjirc/tongjircGoal";
  }

  static const char* value(const ::tongjirc::tongjircGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tongjirc::tongjircGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
uint32 dishwasher_id  # Specify which dishwasher we want to use\n\
";
  }

  static const char* value(const ::tongjirc::tongjircGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tongjirc::tongjircGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dishwasher_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tongjircGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tongjirc::tongjircGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tongjirc::tongjircGoal_<ContainerAllocator>& v)
  {
    s << indent << "dishwasher_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dishwasher_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TONGJIRC_MESSAGE_TONGJIRCGOAL_H
