; Auto-generated. Do not edit!


(cl:in-package tongjirc-msg)


;//! \htmlinclude tongjircFeedback.msg.html

(cl:defclass <tongjircFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_completes
    :reader percent_completes
    :initarg :percent_completes
    :type cl:float
    :initform 0.0))
)

(cl:defclass tongjircFeedback (<tongjircFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <tongjircFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'tongjircFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tongjirc-msg:<tongjircFeedback> is deprecated: use tongjirc-msg:tongjircFeedback instead.")))

(cl:ensure-generic-function 'percent_completes-val :lambda-list '(m))
(cl:defmethod percent_completes-val ((m <tongjircFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tongjirc-msg:percent_completes-val is deprecated.  Use tongjirc-msg:percent_completes instead.")
  (percent_completes m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <tongjircFeedback>) ostream)
  "Serializes a message object of type '<tongjircFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_completes))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <tongjircFeedback>) istream)
  "Deserializes a message object of type '<tongjircFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_completes) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<tongjircFeedback>)))
  "Returns string type for a message object of type '<tongjircFeedback>"
  "tongjirc/tongjircFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'tongjircFeedback)))
  "Returns string type for a message object of type 'tongjircFeedback"
  "tongjirc/tongjircFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<tongjircFeedback>)))
  "Returns md5sum for a message object of type '<tongjircFeedback>"
  "b348798990ac2df8ee8319c093eab504")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'tongjircFeedback)))
  "Returns md5sum for a message object of type 'tongjircFeedback"
  "b348798990ac2df8ee8319c093eab504")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<tongjircFeedback>)))
  "Returns full string definition for message of type '<tongjircFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message ~%float32 percent_completes~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'tongjircFeedback)))
  "Returns full string definition for message of type 'tongjircFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message ~%float32 percent_completes~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <tongjircFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <tongjircFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'tongjircFeedback
    (cl:cons ':percent_completes (percent_completes msg))
))
